### PR TITLE
Added missing batch/agg functions

### PR DESCRIPTION
**Pull request by Spellchaser**
Basically ported over https://github.com/grafana/metrictank/blob/master/expr/seriesaggregators.go

Also removed panics since they all return math.NaN
```
median
def safeMedian(values):
  safeValues = [v for v in values if v is not None]
  if safeValues:
    sortedVals = sorted(safeValues)
    mid = len(sortedVals) // 2
    if len(sortedVals) % 2 == 0:
      return float(sortedVals[mid-1] + sortedVals[mid]) / 2
    else:
      return sortedVals[mid]

diff
def safeDiff(values):
  safeValues = [v for v in values if v is not None]
  if safeValues:
    values = list(map(lambda x: x*-1, safeValues[1:]))
    values.insert(0, safeValues[0])
    return sum(values)

stddev
def safeStdDev(a):
  sm = safeSum(a)
  ln = safeLen(a)
  avg = safeDiv(sm,ln)
  if avg is None: return None
  sum = 0
  safeValues = [v for v in a if v is not None]
  for val in safeValues:
     sum = sum + (val - avg) * (val - avg)
  return math.sqrt(sum/ln)

range
  'range': lambda row: safeSubtract(safeMax(row), safeMin(row)),

multiply
  'multiply': lambda row: safeMul(*row),
def safeMul(*factors):
  if None in factors:
    return None

  factors = [float(x) for x in factors]
  product = reduce(lambda x,y: x*y, factors)
  return product
```

### CODE REVIEW

**Comment by Spellchaser** [comment]
Hmm is there a good way in git? 
I guess I could rebase and throw away commits

**Comment by shanson7** [comment]
Isn't this already based from your feature branch? In which case you can just push it.

**Comment by Spellchaser** [comment]
Nah, I thought this would be separate so they would approve this first as a separate item and then be happy with summarize being stable

**Comment by Spellchaser** [comment]
I based this on upstream/master so I could throw away updates from that base

**Comment by shanson7** [comment]
Ohhhh, ok.

**Pull request merged**
